name: Build Nightly artifacts

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install npm modules
        run: npm ci
      - name: Make envfile
        run: echo "${{ secrets.SENTRY_DSN }}" | base64 -d > .env
      - name: Build artifact
        run: npm_config_yes=true npm run build -- --linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install npm modules
        run: npm ci
      - name: Make envfile
        run: |
          echo ${{ secrets.SENTRY_DSN }} > env.b64
          certutil -decode env.b64 .env
          del env.b64
      - name: Build artifact
        run: env npm_config_yes=true npm run build --win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build portable artifact
        run: env npm_config_yes=true npm run build -- --win portable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install npm modules
        run: npm ci
      - name: Make envfile
        run: echo ${{ secrets.SENTRY_DSN }} | base64 -d > .env
      - name: Build artifact
        run: npm_config_yes=true npm run build -- --mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
